### PR TITLE
Steffi exp

### PR DESCRIPTION
**Pull request by steffilazerte**
Okay, many small changes here

### Notes
- for some reason, Appveyor tests are failing on R devel x64. I'm not overly concerned at this point, but we should probably look into it if it doesn't resolve itself in the future
- the website looks acceptable for now, so we should consider pushing those commits to the master branch so we can preview it on github pages and see if anything needs to be changed

### Vignettes and website
- I've edited the vignettes, added a general_usage one and slimmed down the README
- Your awesome vignette with the use of tidyverse takes at least 5 minutes to run so I moved it to be an article (on the website, with pkgdown) as opposed to a vignette. This means that it doesn't get compiled everytime we run a check.
- I've also added package details to documentation `?weathercan` and links to the article online.

### Coding
- A couple of small bug fixes (including a really obnoxious one that resulted in tests failing ONLY when run by `check()`)
- Added a couple of messages catching missing data, etc.
- Standardized references to stations data frame (now every function has the argument `stn` if required)
- Update NEWS to reflect all the bug fixes and changes
- verbose argument was already present in `weather()`, it reflected a progress indicator. I've added verbose arguments to other functions, as a proxy for a progress bar (progress messages, not a bar, though)
- added `quiet` argument to any function that had messages not controlled by verbose. `quiet` can be used to suppress all messages (Possibly some of those messages should be warnings, but we can think about that later)

### Cran submission prep
- Fixed every NOTE/WARNING in `check()` Hooray!
- Updated cran-comments.md
- Updated appveyor/travis-ci testing
- Added skip_on_cran to stations_all test (longest test) to get the total time down (still around 90s, a bit long)
- Ran the package through win-builder, edited the package Description to fix a couple of notes
- win-builder doesn't like that reference is made to a website that doesn't exist (i.e. the one created by pkgdown) but by the time we submit, this will be fixed

### CODE REVIEW

**Comment by steffilazerte** [comment]
If this goes smoothly and you don't find any more issues, I think we're ready to push to master!

**Comment by boshek** [comment]
This url: "http://bit.ly/2sIuCty" was causing problems and so was this one that it redirected to: "ftp://ftp.tor.ec.gc.ca/Pub/Get_More_Data_Plus_de_donnees/Station%20Inventory%20EN.csv". Instead I needed this one: "ftp://client_climate@ftp.tor.ec.gc.ca/Pub/Get_More_Data_Plus_de_donnees/Station%20Inventory%20EN.csv". My ftp-fu is a little lacking but this seems like a stable link and it works so I think we are good here. 

I must say that you really have done amazing work here. I am so impressed by your efforts here. This is fun.

If tests are passing then I'll  merge.

**Comment by boshek** [comment]
Tests are passing locally; Travis CI is throwing a weird CTAN error which is occurring on another package of mine; Still failing on R devel -64. I will merge to v0.2.2 branch but will hold off pushing to the master until we get all this sorted out.

**Comment by steffilazerte** [comment]
I wonder why the ftp link gave issues? Maybe they changed it? Ah well I guess that is why we run tests!

**Pull request merged**
